### ISSUE TITLE
 ShuttleGPT Unstable

### ISSUE THREAD

**Issue by Askarim04** [shuttlenetwork/shuttle#1]
ShuttleGPT doesn't work, as shown on the screenshot below:
![Screenshot 2023-04-27 1 31 44 PM](https://user-images.githubusercontent.com/132007109/234958899-5f925539-054b-42e7-985e-249654cdf22a.png)

**Comment by liutristan** [comment]
Is that our website or self deployed version?

**Comment by liutristan** [comment]
Fixed shuttleGPT with previous update
