### ISSUE TITLE
Render deployment when using start command node .

### ISSUE THREAD

**Issue by Thesecondalthowcool** [shuttlenetwork/shuttle#17]
When I deploy shuttle on render, I use the build command npm install and the start command node .. But when the deployment gets to node ., it has a error. Any reason why?

**Comment by liutristan** [comment]
its `node.` not `node..`

**Comment by Thesecondalthowcool** [comment]
> its `node.` not `node..`

I know it node.   i just added another . because grammar.

**Comment by Thesecondalthowcool** [comment]
> > its `node.` not `node..`
> 
> I know it node. i just added another . because grammar.

like i did node .

**Comment by liutristan** [comment]
send a screenshot of the error please

**Comment by Thesecondalthowcool** [comment]
> send a screenshot of the error please

![Screenshot 2023-06-04 174634](https://github.com/shuttlenetwork/shuttle/assets/125369193/83923b16-6cf2-4613-b816-85049b121672)

**Comment by liutristan** [comment]
oh

**Comment by liutristan** [comment]
try again, i fixed it

**Comment by Thesecondalthowcool** [comment]
> try again, i fixed it

ok works but now all the pages are glitched other than the home/proxy page

**Comment by Thesecondalthowcool** [comment]
> try again, i fixed it

the games and stuff are in iframe and i think the iframe is broken
