### ISSUE TITLE
render deploy not working pls help

### ISSUE THREAD

**Issue by MicroChipKali** [shuttlenetwork/shuttle#26]

**Comment by liutristan** [comment]
whats the error

**Comment by dandepan303** [comment]
> whats the error

**Hello, sorry for the late response. Here is the error when forking the repository and using the build command `npm install` and the start command `npm start`.  The install works fine but when running `npm start`, this happens:**

==> Starting service with 'npm start' 
 shuttle@3.0.0 start
 node index.js
 
file:///opt/render/project/src/index.js:1
import { createBareServer } from "@tomphttp/bare-server-node";
^^^^^^^^^^^^^^^^
SyntaxError: Named export 'createBareServer' not found. The requested module '@tomphttp/bare-server-node' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from '@tomphttp/bare-server-node';
  const { createBareServer } = pkg;
  
at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)
at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
at async loadESM (node:internal/process/esm_loader:40:7)
at async handleMainPromise (node:internal/modules/run_main:66:12)
  
  Node.js v20.5.0

**I have also found that by cloning the repository locally and using the same commands, the same error occurs. I am currently trying to find a fix and may send a PR soon, but if you can figure something out, I trust your code more than my own 😆**

**Comment by liutristan** [comment]
try downgrading node.js version to v18.***

**Comment by liutristan** [comment]
im using v18.17.0 for my vps and it works

**Comment by dandepan303** [comment]
Ok will do.

**Comment by dandepan303** [comment]
It turns out render has a read-only file system that needs sudo. This means that I cannot downgrade the node version.

**Comment by liutristan** [comment]
try again, i think i fixed it

**Comment by dandepan303** [comment]
It works. Thank you!
