### ISSUE TITLE
Error: This site can't be reached

### ISSUE THREAD

**Issue by ask-arim** [shuttlenetwork/shuttle#28]
Error: This site can't be reached (shown in screenshots below):
![Screenshot 2023-08-22 4 11 32 PM](https://github.com/shuttlenetwork/shuttle/assets/111149452/fc9d7e11-80f9-42ab-ae3a-ec19e306c030)
![Screenshot 2023-08-22 4 12 25 PM](https://github.com/shuttlenetwork/shuttle/assets/111149452/797a9266-a385-4466-b9cc-4d4e7b9b0ba9)
![Screenshot 2023-08-22 4 13 02 PM](https://github.com/shuttlenetwork/shuttle/assets/111149452/82d51b3c-0f1c-4f38-a447-5fc6ccc3ba34)
![Screenshot 2023-08-22 4 13 13 PM](https://github.com/shuttlenetwork/shuttle/assets/111149452/b46b8fa4-ad57-4921-90a8-7c4ad26f689f)
![Screenshot 2023-08-22 4 13 26 PM](https://github.com/shuttlenetwork/shuttle/assets/111149452/a6a9bcd8-6955-4f36-b5ce-86eff501751f)

**Comment by tristandevs** [comment]
use another domain, can you join discord.gg/xi and make a ticket.

**Comment by tristandevs** [comment]
try tristanschools.co

**Comment by ask-arim** [comment]
ok thank you so much
