### ISSUE TITLE
What should I use to deploy Shuttle

### ISSUE THREAD

**Issue by MrDynamite50** [shuttlenetwork/shuttle#3]
Everywhere it is either blocked or taken down please add a way to import to google sites if possible or some more ways to deploy.

**Comment by liutristan** [comment]
you can't deploy to google sites

**Comment by liutristan** [comment]
google sites is for building sites by dragging stuff

**Comment by MrDynamite50** [comment]
Ok but still is there any other place to possibly deploy it to?

**Comment by liutristan** [comment]
onrender and cyclic works super good

**Comment by oHeckGage** [comment]
Replit is a good option, and Railway is the one that most use. Just use the deploy buttons and see what is best for you 🤷‍♂️

**Comment by liutristan** [comment]
replit is not, it will crash
