### ISSUE TITLE
Breaking Bad doesn't have its own episodes

### ISSUE THREAD

**Issue by marbles0da84** [shuttlenetwork/shuttle#38]
Hello, I am not sure this is an issue that is worth sharing, but every time I try to watch Breaking Bad on the website, all of the episodes show up as a movie called "Mirror." I've looked into more of the TV shows and movies, and some have simply not worked, such as Regular Show, saying it isn't available.

Besides this personal issue, compliments to the chefs, this website has been great to use!

**Comment by tristandevs** [comment]
im going to fix soon when tv api v2 releases

**Comment by findyourwings** [comment]
I'd recommend using FMHY's list of [video piracy services](https://fmhy.pages.dev/videopiracyguide/) in the meantime, if you experience issues similar to this in the future.
