### ISSUE TITLE
is there a way to make it available to vercel

### ISSUE THREAD

**Issue by rhino42811** [shuttlenetwork/shuttle#41]
I only know how to create links using Vercel, since Render keeps suspending me. Can you try to make it work on Vercel instead?

**Comment by tristandevs** [comment]
try forking this repo and make a new acc

**Comment by PurePro4561** [comment]
Yeah, I forked it, but render still suspended me

**Comment by UltiGame2890** [comment]
Yo it’s purepro!!

**Comment by tristandevs** [comment]
try using https://hop.io/
its alot better and dont ban accs

**Comment by mdoryammilwalrus** [comment]
You can't create proxies on Vercel

**Comment by PurePro4561** [comment]
How much does hop.io cost

**Comment by UltiGame2890** [comment]
@rhino42811 add vercel.json and put this code: {
  "version": 2,
  "builds": [{
      "src": "index.js",
      "use": "@vercel/node"
  }],
  "routes": [{
      "src": "/(.*)",
      "dest": "index.js"
  }]
}

Then try deploying it

**Comment by rhino42811** [comment]
do you add it into the github

**Comment by rhino42811** [comment]
> You can't create proxies on Vercel

yes you can I do it for intersteller and artclass
