### ISSUE TITLE
Deploying issues

### ISSUE THREAD

**Issue by jack9192** [shuttlenetwork/shuttle#46]
I have tried to deploy on Render, Glitch, and Cyclic and it hasn't worked on any of them. Render says; "action is not allowed". Cyclic doesn't allow it because it is a proxy. Glitch doesn't load. I can't use any of the other services. What should I do?

**Comment by gagedevs** [comment]
@jack9192 Get a VPS, and deploy it there. If you follow this route and you need help, make a ticket in the Discord and ping @xgage.

Or, purchase a domain and in the Discord, follow the instructions in the #byod channel to add it to Cloudflare and enable SSL.

**Comment by tristandevs** [comment]
hop.sh
