### ISSUE TITLE
deployment on heroku don’t work for some reason 

### ISSUE THREAD

**Issue by erixklol** [shuttlenetwork/shuttle#5]
look here’s proof 
![F51E2FDF-85B8-41EE-865F-E49293DA4ECE](https://user-images.githubusercontent.com/127577386/235387029-9730d4ce-7777-4924-aed2-9a98b2c34f32.png)

**Comment by liutristan** [comment]
idk why

**Comment by liutristan** [comment]
i think heroku is paied now, are you paying for heroku

**Comment by liutristan** [comment]
ill try making a app.json later

**Comment by erixklol** [comment]
> for 
Yes

**Comment by erixklol** [comment]
yep I’m paying for heroku rn

**Comment by liutristan** [comment]
can you try again

**Comment by liutristan** [comment]
i added app.json

**Comment by erixklol** [comment]
uhhhh it errors at run script and dyknows ![image](https://user-images.githubusercontent.com/127577386/235799790-5cf1ebd4-a8c3-40dc-af27-8709d30f38d4.png)

**Comment by liutristan** [comment]
uh

**Comment by liutristan** [comment]
you can try cyclic instead or onrender if you want

**Comment by liutristan** [comment]
idk why heroku is acting like that

**Comment by erixklol** [comment]
man cyclic or onrender always blocked for me

**Comment by liutristan** [comment]
oh

**Comment by erixklol** [comment]
imma try code sand box

**Comment by liutristan** [comment]
alr

**Comment by liutristan** [comment]
ill try testing on heroku

**Comment by liutristan** [comment]
nvm

**Comment by erixklol** [comment]
csb don’t work too

**Comment by erixklol** [comment]
rip
